### ISSUE TITLE
Dockerhub image run failing

### ISSUE THREAD

**Issue by kleo** [frankbaele/mindustry#3]
On using

`docker run -ti -p 6567:6567/tcp -p 6567:6567/udp frankbaele/mindustry`

Error: Invalid or corrupt jarfile server-release.jar

No problems on docker build.

**Comment by frankbaele** [comment]
Thx for the report Kleo,

It seems that something went wrong in the build of the docker. I'm force rebuilding it and this should fix the issue

Frank
